name: Build and Publish JAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Generate version based on current time
        id: version
        run: |
          TIMESTAMP=$(date +%s%N | cut -b1-13) # Current time in milliseconds
          SHORT_VERSION=${TIMESTAMP: -5} # Trim to the last 5 digits
          echo "VERSION=1.0.$SHORT_VERSION" >> $GITHUB_OUTPUT

      - name: Update POM version
        run: |
          mvn versions:set -DnewVersion=${{ steps.version.outputs.VERSION }}
          mvn versions:commit

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}