name: Build and Publish JAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Calculate new version based on timestamp
        id: version
        run: |
          BASE_VERSION="1.0"
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          NEW_VERSION="${BASE_VERSION}.${TIMESTAMP}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update POM version
        run: |
          mvn versions:set -DnewVersion=${{ steps.version.outputs.NEW_VERSION }}
          mvn versions:commit

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Tag
        run: |
          git tag ${{ steps.version.outputs.NEW_VERSION }}
          git push origin ${{ steps.version.outputs.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}