name: Build and Publish JAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Calculate new version
        id: version
        run: |
          LAST_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.1.0")
          NEW_VERSION=$(echo $LAST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update POM version
        run: |
          mvn versions:set -DnewVersion=${{ steps.version.outputs.NEW_VERSION }}
          mvn versions:commit

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new version tag
        run: |
          git add pom.xml
          git commit -m "Bump version to ${{ steps.version.outputs.NEW_VERSION }}"
          git push
          git tag ${{ steps.version.outputs.NEW_VERSION }}
          git push --tags